package edu.illinois.cs.cogcomp.tutorial;

import edu.illinois.cs.cogcomp.tutorial.datastruct.ConllRawToken;
import edu.illinois.cs.cogcomp.tutorial.datastruct.ConllRelation;

/**
 * Created by i-danielk on 6/7/15.
 */

/**
 * This class shows how to use the classes generated by LBJ programmatically.
 */
public class testEntityRelationClassifier {
    /**
     * testing independent classifiers individually
     */
    public static void independentClassifiers() {
        System.out.println("Start to test the organiziation classifier ... ");
        OrganizationClassifier orgClassifier = new OrganizationClassifier();
        Conll04_RelationReaderNew cr = new Conll04_RelationReaderNew("data/conll04.corp", "Token");
        ConllRawToken entity = (ConllRawToken) cr.next();
        while( entity != null ) {
            System.out.println(entity);
            System.out.println(orgClassifier.discreteValue(entity));
            entity = (ConllRawToken) cr.next();
        }

        System.out.println("Start to test the organiziation classifier ... ");
        PersonClassifier personClassifier = new PersonClassifier();
        cr = new Conll04_RelationReaderNew("data/conll04.corp", "Token");
        entity = (ConllRawToken) cr.next();
        while( entity != null ) {
            System.out.println(entity);
            System.out.println(personClassifier.discreteValue(entity));
            entity = (ConllRawToken) cr.next();
        }

        work_forClassifier worksForRelationClassifier = new work_forClassifier();
        cr = new Conll04_RelationReaderNew("data/conll04.corp", "Pair");
        System.out.println("Starting to classify the instances ... ");

        ConllRelation relation = (ConllRelation) cr.next();
        System.out.println(relation.toString());
        while( relation != null ) {
            System.out.println(relation);
            System.out.println(worksForRelationClassifier.discreteValue(relation));
            relation = (ConllRelation) cr.next();
        }
    }

    /**
     * testing the joint classifier
     */
    public static void jointClassifiers() {
        System.out.println("Start to initialize the classifier ... ");
        RelArgsClassifier relArgClassifier = new RelArgsClassifier();
        Arg_pClassifier argpClassifier = new Arg_pClassifier();
        ArgOClassifier argOClassifier = new ArgOClassifier();


        Conll04_RelationReaderNew cr = new Conll04_RelationReaderNew("data/conll04.corp", "Pair");
        System.out.println("Starting to classify the instances ... ");
        ConllRelation pair = (ConllRelation) cr.next();
        while( pair != null ) {
            System.out.println(pair);
            pair = (ConllRelation) cr.next();
            System.out.println(relArgClassifier.discreteValue(pair));
//            System.out.println(argpClassifier.discreteValue(tok));
//            System.out.println(argpClassifier.discreteValue(tok));
        }
    }

    public static void main(String[] args) {
        //independentClassifiers();
        jointClassifiers();
    }
}
