/**
 * This software is released under the University of Illinois/Research and
 *  Academic Use License. See the LICENSE file in the root folder for details.
 * Copyright (c) 2016
 *
 * Developed by:
 * The Cognitive Computations Group
 * University of Illinois at Urbana-Champaign
 * http://cogcomp.cs.illinois.edu/
 */
package edu.illinois.cs.cogcomp.lbjava.examples.entityRelation;

import edu.illinois.cs.cogcomp.lbjava.examples.entityRelation.datastruct.ConllRawToken;
import edu.illinois.cs.cogcomp.lbjava.examples.entityRelation.datastruct.ConllRelation;

/**
 * This class shows how to use the classes generated by LBJ programmatically.
 */
public class testEntityRelationClassifier {
    /**
     * testing independent classifiers individually
     */
    public static void independentClassifiers() {
        System.out.println("Start to test the organiziation classifier ... ");
        OrganizationClassifier orgClassifier = new OrganizationClassifier();
        Conll04_RelationReaderNew cr = new Conll04_RelationReaderNew("data/conll04.corp", "Token");
        ConllRawToken entity = (ConllRawToken) cr.next();
        while( entity != null ) {
            System.out.println(entity);
            System.out.println(orgClassifier.discreteValue(entity));
            entity = (ConllRawToken) cr.next();
        }

        System.out.println("Start to test the organiziation classifier ... ");
        PersonClassifier personClassifier = new PersonClassifier();
        cr = new Conll04_RelationReaderNew("data/conll04.corp", "Token");
        entity = (ConllRawToken) cr.next();
        while( entity != null ) {
            System.out.println(entity);
            System.out.println(personClassifier.discreteValue(entity));
            entity = (ConllRawToken) cr.next();
        }

        work_forClassifier worksForRelationClassifier = new work_forClassifier();
        cr = new Conll04_RelationReaderNew("data/conll04.corp", "Pair");
        System.out.println("Starting to classify the instances ... ");

        ConllRelation relation = (ConllRelation) cr.next();
        System.out.println(relation.toString());
        while( relation != null ) {
            System.out.println(relation);
            System.out.println(worksForRelationClassifier.discreteValue(relation));
            relation = (ConllRelation) cr.next();
        }
    }

    /**
     * testing the joint classifier
     */
    public static void jointClassifiers() {
        System.out.println("Start to initialize the classifier ... ");
        RelArgsClassifier relArgClassifier = new RelArgsClassifier();
        Arg_pClassifier argpClassifier = new Arg_pClassifier();
        ArgOClassifier argOClassifier = new ArgOClassifier();


        Conll04_RelationReaderNew cr = new Conll04_RelationReaderNew("data/conll04.corp", "Pair");
        System.out.println("Starting to classify the instances ... ");
        ConllRelation pair = (ConllRelation) cr.next();
        while( pair != null ) {
            System.out.println(pair);
            pair = (ConllRelation) cr.next();
            System.out.println(relArgClassifier.discreteValue(pair));
//            System.out.println(argpClassifier.discreteValue(tok));
//            System.out.println(argpClassifier.discreteValue(tok));
        }
    }

    public static void main(String[] args) {
        independentClassifiers();
        //jointClassifiers();
    }
}
