/**
 * This software is released under the University of Illinois/Research and Academic Use License. See
 * the LICENSE file in the root folder for details. Copyright (c) 2016
 *
 * Developed by: The Cognitive Computations Group, University of Illinois at Urbana-Champaign
 * http://cogcomp.cs.illinois.edu/
 */
package edu.illinois.cs.cogcomp.lbjava.infer;

import java.util.Vector;


/**
 * Anonymous inner classes extending this class are instantiated by the code generated by the LBJava
 * compiler when creating <code>FirstOrderConstraint</code> representations. The methods of this
 * class are used to compute new values for the arguments of quantified constraint expressions.
 *
 * @see edu.illinois.cs.cogcomp.lbjava.infer.FirstOrderConstraint
 * @author Nick Rizzolo
 **/
abstract public class ArgumentReplacer {
    /**
     * The settings of non-quantification variables in context at the equality in question.
     **/
    protected Object[] context;
    /**
     * The settings of quantification variables in context at the equality in question.
     **/
    protected Vector quantificationVariables;


    /**
     * Initializing constructor.
     *
     * @param c The context of the corresponding quantified constraint expression, except for
     *        quantification variables.
     **/
    public ArgumentReplacer(Object[] c) {
        context = c;
    }


    /**
     * Provides the settings of quantification variables.
     *
     * @param q The settings of quantification variables.
     **/
    public void setQuantificationVariables(Vector q) {
        quantificationVariables = q;
    }
}
